### ISSUE TITLE
cannot find files

### ISSUE THREAD

**Issue by boyuan-zhang** [ElementoLab/imc#15]
Dear
I am not sure this is correct or not, but when I set 
TIFFS=processed/${SAMPLE}/tiffs/${SAMPLE}*_full.tiff
the following step cannot locate the full.tiff files. Can you help me with it?
[Errno 2] No such file or directory: '/processed/20200612_FLU_1923/tiffs/*_full.tiff'

**Comment by afrendeiro** [comment]
Hello,

What is exactly the command being run?
What is the larger context of the error message?
What OS and Python version are you using?
